# Generated by Django 5.2.11 on 2026-03-16 15:09

import Audit.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0005_alter_owl_upload_file_alter_owl_upload_configs_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owl_upload_configs',
            name='file',
        ),
        migrations.AddField(
            model_name='owl_upload_configs',
            name='configs',
            field=models.JSONField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='owl_upload',
            name='file',
            field=models.FileField(storage=Audit.models.PrivateMediaStorage(), upload_to='owl_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rdf', 'xml', 'owl'])]),
        ),
    ]
