# Generated by Django 5.1.1 on 2026-02-16 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('total', models.IntegerField(default=0)),
                ('iri', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('depth', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('order', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='Audit.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField(blank=True, null=True)),
                ('max', models.FloatField(blank=True, null=True)),
                ('inverse', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='type_question_set', to='Audit.category')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.TextField(blank=True, null=True)),
                ('question', models.TextField(default=None, null=True)),
                ('weight', models.FloatField(default=1, null=True)),
                ('group', models.CharField(default='', max_length=256, null=True)),
                ('answerType', models.CharField(choices=[('yes_no', 'Yes/No'), ('interval', 'Interval'), ('likert', 'Likerta')], default='yes_no', max_length=50)),
                ('likerta', models.JSONField(blank=True, null=True)),
                ('condition', models.ManyToManyField(default=None, related_name='condition_set', to='Audit.condition')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_question', to='Audit.question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='', null=True)),
                ('user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='Audit.question')),
            ],
        ),
        migrations.CreateModel(
            name='Subthemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iri', models.TextField(blank=True, null=True)),
                ('name', models.CharField(default=None, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('subtheme', models.ManyToManyField(blank=True, default=None, related_name='subthemes', to='Audit.subthemes')),
                ('type', models.ManyToManyField(related_name='subtheme_type', to='Audit.category')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='subtheme',
            field=models.ManyToManyField(related_name='question_set', to='Audit.subthemes'),
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_audit_tree', models.JSONField(null=True)),
                ('last_recalculated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(blank=True, default=None, related_name='user_category', to='Audit.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0)),
                ('mandatoryTrue', models.FloatField(default=0)),
                ('mandatoryFalse', models.FloatField(default=0)),
                ('true', models.FloatField(default=0)),
                ('false', models.FloatField(default=0)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_answer', to='Audit.category')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_score', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'category')},
            },
        ),
    ]
