# Generated by Django 5.2.11 on 2026-03-15 10:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0002_question_hint'),
    ]

    operations = [
        migrations.CreateModel(
            name='OWL_Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='superuser_only/owl_uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rdf', 'xml', 'owl'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OWL_Upload_Configs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='superuser_only/owl_upload_configs/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['json'])])),
            ],
        ),
    ]
