# Generated by Django 5.2.11 on 2026-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0003_owl_upload_owl_upload_configs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owl_upload',
            name='file',
            field=models.FileField(upload_to='superuser_only/owl_uploads/'),
        ),
    ]
