# Generated by Django 5.2.11 on 2026-03-15 11:08

import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0004_alter_owl_upload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owl_upload',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/silve/Desktop/work/NewStarT_Audit/superuser_only/owl_uploads'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rdf', 'xml', 'owl'])]),
        ),
        migrations.AlterField(
            model_name='owl_upload_configs',
            name='file',
            field=models.FileField(upload_to=pathlib.PureWindowsPath('C:/Users/silve/Desktop/work/NewStarT_Audit/superuser_only/owl_upload_configs'), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['rdf', 'xml', 'owl'])]),
        ),
    ]
