# Generated by Django 5.2.11 on 2026-03-16 16:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0006_remove_owl_upload_configs_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owl_upload_configs',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
