# Generated by Django 5.2.11 on 2026-03-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0007_owl_upload_configs_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owl_upload_configs',
            name='configs',
            field=models.TextField(),
        ),
    ]
