# Generated by Django 5.2.11 on 2026-03-22 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audit', '0008_alter_owl_upload_configs_configs'),
    ]

    operations = [
        migrations.AddField(
            model_name='owl_upload_configs',
            name='name',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
